### ISSUE TITLE
Error in basic substraction function

### ISSUE THREAD

**Issue by fingenerf** [MASKOR/gologpp#28]
The call
`log_error(to_string(3 - 1 + 2))`
returns 0 instead of 4. Probably because the function resolves to: 3 - ( 1 + 2 )

**Comment by vmatare** [comment]
yes precisely, the parser is right-associative and also doesn't implement operator precedence. Until this is fixed, it is important to brace everything to enforce correct evaluation order.

**Comment by vmatare** [comment]
Should be fixed by 0b065e7 in master and by 79c768f in the stable branch
